root = "."
tmp_dir = "tmp"

[build]
    bin = "./tmp/htmx-templ-app-template"
    cmd = "go build -tags dev -o ./tmp/htmx-templ-app-template ."
    delay = 20
    exclude_dir = ["public", "tmp", "bin", "node_modules"]
    exclude_file = []
    exclude_unchanged = false
    follow_symlink = false
    full_bin = ""
    include_dir = []
    include_ext = ["go", "tpl", "tmpl", "templ", "html", "env", "js", "csv", "pkl", "conf"]
    kill_delay = "0s"
    log = "build-errors.log"
    send_interrupt = false
    stop_on_error = true
    args_bin = ["server", "--config-file", "config/dev.pkl"]

[color]
    app = ""
    build = "yellow"
    main = "magenta"
    runner = "green"
    watcher = "cyan"
[log]
    time = false

[misc]
    clean_on_exit = false
